### PR TITLE
Feature/add http support

### PR DESCRIPTION
**Pull request by jkburges**
In order to enable remote probing.

### CODE REVIEW

**Comment by jkburges** [comment]
Sorry, wrong origin :-)

**Comment by binoculars** [comment]
If you get the fontconfig problem done, please let me know

**Comment by jkburges** [comment]
> If you get the fontconfig problem done, please let me know

I'm not sure what you mean by this. 

My intent is just to get a build that supports http(s) (as in https://github.com/binoculars/ffmpeg-build-lambda/pull/1), but I accidentally put a PR up against this repo instead of my own fork (because I know that you don't want http here).

**Comment by binoculars** [comment]
That's fine. My nightly builds have been failing: https://travis-ci.org/binoculars/ffmpeg-build-lambda/builds/291807856

they changed some fontconfig option, but I haven't had a chance to mess with it.

**Comment by jkburges** [comment]
Ah, I see.  

Well, I got a build to work, based off the changes in  https://github.com/binoculars/ffmpeg-build-lambda/pull/1 and rebased on to 844d7b3d4c79aa8d0670cda01a5e77c624953df7, and the build worked, so you're welcome to see what's different there.

See: https://github.com/Biteable/ffmpeg-build-lambda and https://travis-ci.org/Biteable/ffmpeg-build-lambda/builds/291919370

**Pull request closed without merging**
